
services:
  nginx:
    image: nginx:alpine
    ports:
      - 5000:5000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - distributed

  distributed:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    environment:
      - ConnectionStrings__Redis=cache_redis:6379
      - ASPNETCORE_URLS=http://+:5000

  redis:
    image: redis:latest
    container_name: cache_redis